name: Backend CI

on:
  push:
    branches: [ "master", "develop", "release/rc-1" ]
  pull_request:
    branches: [ "master", "develop", "release/rc-1" ]

jobs:
  start:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! $GITHUB_ACTION_PATH $GITHUB_WORKSPACE"
        env:
          First_Name: Mona
