name: Backend CI

on:
  push:
    branches: [ "master", "develop", "release/rc-1" ]
  pull_request:
    branches: [ "master", "develop", "release/rc-1" ]

jobs:
  start:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Moved in folder
        run: cd ../../backend
      - name: Install dependencies
        run: npm ci
      - name: Start lint
        run: npm run lint
      - name: Start server
        run: npm run start
