name: Backend CI

on:
  push:
    branches: [ "master", "develop", "release/rc-1" ]
  pull_request:
    branches: [ "master", "develop", "release/rc-1" ]

jobs:
  start-on-ubuntu:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Start lint
        run: npm run lint
      - name: Start tests
        run: npm run test
        
        
  start-on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Move in folder
        run: cd backend
      - name: Install dependencies
        run: npm i
      - name: Move in folder
        run: cd backend
      - name: Start lint
        run: npm run lint
      - name: Move in folder
        run: cd backend
      - name: Start server
        run: npm run start
        
  start-on-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Move in folder
        run: cd backend
      - name: Install dependencies
        run: npm i
      - name: Move in folder
        run: cd backend
      - name: Start lint
        run: npm run lint
      - name: Move in folder
        run: cd backend
      - name: Start server
        run: npm run start
