name: Backend CI

on:
  push:
    branches: [ "master", "develop", "release/rc-1" ]
  pull_request:
    branches: [ "master", "develop", "release/rc-1" ]

jobs:
  start:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - name: Clone rep
        uses: actions/checkout@v3
      - name: "Comm"
        run: ls -la
