name: Frontend CI

on:
  push:
    branches: [ "task/*", "bugfix/*" ]
  pull_request:
    branches: [ "master", "develop", "release/*", "feature/*" ]

jobs:
  start-on-ubuntu:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./frontend
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Start lint
        run: npm run lint
      - name: Start build
        run: npm run build
               
  start-on-windows:
    runs-on: windows-latest
    defaults:
        run:
          working-directory: ./frontend
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Start lint
        run: npm run lint
      - name: Start build
        run: npm run build
        
  start-on-macos:
    runs-on: macos-latest
    defaults:
        run:
          working-directory: ./frontend
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Start lint
        run: npm run lint
      - name: Start build
        run: npm run build
